### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by danbarua** [eVisionSoftware/OpenSourcePolicy#2]
> This document is released under the Creative Commons Attribution-ShareAlike (CC BY-SA)
> 
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

We added an attribution note in our fork https://github.com/BusinessSystemsLtd/OpenSourcePolicy/commit/a0778133bd8ee92601dbdb52de1201b7bfefe43b, but you may want to consider adding a header or something like that to the original source?

**Comment by damianh** [comment]
Not sure what you mean @danbarua ? What would it look like?

**Comment by ilyapalkin** [comment]
x
